/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import org.example.person.Administrator;
import org.example.person.Cashier;
import org.example.person.Customer;
import org.example.person.Manager;
import org.example.person.Person;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        List<Person> people = initializePeople();
        for (Person p : people) {
            System.out.println(p);
        }
    }

    private static List<Person> initializePeople() {
        List<Person> people = new ArrayList<>();
        people.add(new Customer("Alice"));
        people.add(new Customer("Bob"));
        people.add(new Cashier("Charlie", 1));
        people.add(new Manager("David", 2));
        people.add(new Administrator("Eve", 3));
        return people;
    }
}
